# Based on: https://github.com/cluster-apps-on-docker/spark-standalone-cluster-on-docker

version: "3.6"

services:

  # Jupyterlab service with pyspark installed. The container will bind the folder shared-workspace, in this way
  # it's possible to pass the notebooks to Jupyterlab directly.
  jupyterlab:
    image: andreper/jupyterlab:3.0.0-spark-3.0.0
    container_name: jupyterlab
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - ./shared-workspace:/opt/workspace

  spark-master:
    image: andreper/spark-master:3.0.0
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - ./shared-workspace:/opt/workspace

  # In this case, we only have a cluster of two nodes, each one having one core and 2Gb of RAM.
  # If you want more nodes in the cluster, you can just clone one of these nodes and set the correct port
  # (XXXX:8081) on the container
  spark-worker-1:
    image: andreper/spark-worker:3.0.0
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2G
    ports:
      - 8081:8081
    volumes:
      - ./shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-2:
    image: andreper/spark-worker:3.0.0
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2G
    ports:
      - 8082:8081
    volumes:
      - ./shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  # Single Neo4j Instance, if you don't have a Neo4j instance to work with
#  neo4j:
#    image: neo4j:4.4.10-enterprise
#    hostname: neo4j
#    container_name: neo4j
#    ports:
#      - "7474:7474" #HTTP
#      - "7687:7687" #Bolt
#      - "7473:7473" #HTTPS
#    environment:
#      - NEO4J_AUTH=neo4j/test
#      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
#      - NEO4J_dbms_connector_http_listen__address=:7474
#      - NEO4J_dbms_connector_https_listen__address=:7473
#      - NEO4J_dbms_connector_bolt_listen__address=:7687
#      - NEO4J_dbms_allow__upgrade=true
#      - NEO4JLABS_PLUGINS=["apoc"]
#      - NEO4J_dbms_logs_query_enabled=INFO
#      - NEO4J_dbms_logs_query_parameter__logging__enabled=true
